document.getElementById('Audio').innerHTML = "<h1>Banque de son</h1>"
+"<main>"
+" <article>"
+" <h4>Chien</h4>"
+" <audio controls autoplay muted>"
+'<source src="audio/dog2.mp3" type="audio/mp3">'
+"</audio>"
+"<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores provident inventore voluptatibus cumque minima dicta suscipit architecto, nostrum maxime quo cupiditate harum! Reprehenderit mollitia error, quidem temporibus nobis laboriosam illum!</p>"
+"</article>"
+"<article>"
+"<h4>Kobudaï</h4>"
+"<audio controls>"
+'<source src="audio/whalesurfaces.mp3" type="audio/mp3">'
+"</audio>"
+"<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores provident inventore voluptatibus cumque minima dicta suscipit architecto, nostrum maxime quo cupiditate harum! Reprehenderit mollitia error, quidem temporibus nobis laboriosam illum!</p>"
+"</article>"
+"<article>"
+"<h4>Chat</h4>"
+"<audio controls>"
+'<source src="audio/BOB-CAT.mp3" type="audio/mp3">'
+" </audio>"
+" <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores provident inventore voluptatibus cumque minima dicta suscipit architecto, nostrum maxime quo cupiditate harum! Reprehenderit mollitia error, quidem temporibus nobis laboriosam illum!</p>"
+" </article>"
+"    <article>"
+"  <h4>Chien 2</h4>"
+" <audio controls>"
+'<source src="audio/chasdog.mp3" type="audio/mp3">'
+"</audio>"
+"<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maiores provident inventore voluptatibus cumque minima dicta suscipit architecto, nostrum maxime quo cupiditate harum! Reprehenderit mollitia error, quidem temporibus nobis laboriosam illum!</p>"
+" </article>"
+"</main>"