document.getElementById('Contact').innerHTML = '<h1>Contact</h1>'
+'<main>'
+'<form>'
+'<p>'
+'<label for="t1">Quel est votre Nom ?<abbr title="Ce champ est obligatoire">*</abbr></label>'
+'<input type="text" id="t1" name="Nom" required>'
+' </p>'
+'<p>'
+'<label for="t2">Quelle est votre adresse électronique ?</label>'
+'<input type="email" id="t2" name="email">'
+' </p>'
+' <p>'
+'<label for="t3">Quelle est votre numéro de téléphone ?</label>'
+'<input type="tel" id="t3" name="tel" pattern="[0-9]{10}">'
+'</p>'
+' <p>'
+' <label for="t4">Laissez un court message</label>'
+'<textarea id="t4" name="msg" maxlength="140" rows="5" required></textarea>'
+'</p>'
+'<p>'
+' <button>Envoyer</button>'
+' </p>'
+'</form>'
+'</main>'